<div id="flashs" class="alert alert-danger fixed-bottom text-center" style="display: none"  >

</div>

<h2>Users</h2>

<button id="new_user" type="button" class="btn btn-outline-success btn-sm m-3"><i class="fas fa-plus"></i> Add user</button>
<form id="new_user_form" style="display: none" method="post" class="form-block " action="/add">
    <h3>Add user</h3>
    <div class="row mt-3 mb-3">
        <div class="col-10">
            <input required name="name" class="form-control input-sm" value="" placeholder="name">
            <input required type="email" name="email" class="form-control input-sm" value="" placeholder="email">
            <input required type="password"  name="password" class="form-control input-sm" value="" placeholder="password">
            <input required name="role" class="form-control input-sm" value="" placeholder="role">
        </div>

        <div class="col-2">
            <div class="">
                <button type="submit" class="btn btn-outline-success btn-sm mb-5"><i class="fas fa-save"></i> Save</button>
            </div>
            <div class="">
                <button id="new_user_hide" type="button" class="btn btn-outline-danger btn-sm m-2 mt-5"><i class="fas fa-minus"></i> Hide </button>
            </div>
        </div>
    </div>
</form>



<form id="edit_user_form" style="display: none" method="post" class="form-block " action="/update">
    <h3>Edit user</h3>
    <div class="row mt-3 mb-3">
        <div class="col-10">
            <input id="edit_user_id" type="hidden" name="user_id" >
            <input id="edit_user_name" required name="user_name" class="form-control input-sm" placeholder="name" >
            <input id="edit_user_email" required name="user_email" class="form-control input-sm" placeholder="email">
            <input id="edit_user_password" name="user_password" class="form-control input-sm" placeholder="Type here the new password if you want to change the old one." >
            <input id="edit_user_role" required name="user_role" class="form-control input-sm" placeholder="role" >
        </div>
        <div class="col-2">
            <div class="">
                <button type="submit" class="btn btn-outline-success btn-sm mb-5"><i class="fas fa-save"></i> Save</button>
            </div>
            <div class="">
                <button id="edit_user_hide" type="button" class="btn btn-outline-danger btn-sm  mt-5 "><i class="fas fa-minus"></i> Hide </button>
                </div>
        </div>
    </div>
</form>

    <div class="container">
        <nav aria-label="Page navigation example" >
            <ul class="pagination justify-content-center">
                <?php foreach ($pagination->buttons as $button) :?>
                    <li <?=$button->isActive ? 'class="page-item"' : 'class="page-item disabled"' ?> >
                        <?php if ($button->isActive) : ?>
                            <?php if ($button->isActive) : ?>
                                <a class="page-link" href="/users?page=<?=$button->page?>&amp;tag=<?=$tag?>"><?=$button->text?></a>
                            <?php else : ?>
                                <a class="page-link" href="/users?page=<?=$button->page?>"><?=$button->text?></a>
                            <?php endif ?>
                        <?php else : ?>
                            <span class="page-link page-item disabled" aria-hidden="true"><?=$button->text?></span>
                        <?php endif ?>
                    </li>
                <?php endforeach ?>
            </ul>
        </nav>

        <div class="row" style="min-height:400px; ">
            <div class="col-12">

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">name</th>
                        <th scope="col">email</th>
                        <th scope="col">role</th>
                        <th scope="col">action</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($users as $user) :?>
                            <tr id="<?=$user->getId()?>" >
                                <th scope="row">
                                    <?=$user->getName()?>
                                </th>
                                <td>
                                    <?=$user->getEmail()?>
                                </td>
                                <td>
                                    <?=$user->getRole()?>
                                </td>
                                <td>
                                    <span class="edit" title="edit"
                                          data-user_id="<?=$user->getId()?>"
                                          data-user_name="<?=$user->getName()?>"
                                          data-user_email="<?=$user->getEmail()?>"
                                          data-user_role="<?=$user->getRole()?>">
                                    <i class="fas fa-edit"></i>
                                    </span>
                                    <span class="del" title="delete" data-delete_user="true" data-user_id="<?=$user->getId()?>" data-user_name="<?=$user->getName()?>" ><i class="fas fa-trash-alt"></i></span>
                                </td>
                            </tr>
                       <?php endforeach?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<script>
    $(document).ready(function(){

        $(".edit").click(function() {
            var user_id = $(this).data('user_id');
            var user_name = $(this).data('user_name');
            var user_email = $(this).data('user_email');
            var user_role = $(this).data('user_role');
            $("#edit_user_form").fadeIn();
            $("#edit_user_id").val(user_id);
            $("#edit_user_name").val(user_name);
            $("#edit_user_email").val(user_email);
            $("#edit_user_role").val(user_role);

        });
        $("#edit_user_hide").click(function() {
            $("#edit_user_form").hide()

        });

        $("#new_user").click(function(){
            $("#new_user_form").fadeIn()
            $("#new_user").hide()
        });
        $("#new_user_hide").click(function(){
            $("#new_user_form").hide()
            $("#new_user").fadeIn()
        });


        $(".del").click(function(){
            var delete_user = $(this).data('delete_user');
            var user_id = $(this).data('user_id');
            var user_name = $(this).data('user_name');

            var data = {
                delete_user : delete_user,
                user_id : user_id,
                user_name : user_name,
            };

            if (confirm("Ви впевнені що хочете видалити користувача " + user_name + '?')){
                $.ajax({
                    url: '/delete',
                    method: "post",
                    data: data,
                    success: function (res) {
                        console.log(res.data.response);
                        console.log(res);
                        $('[id=' + user_id + ']').remove();

                        $('#flashs').fadeIn().text(res.data.response);
                        setTimeout(function(){
                            $('#flashs').fadeOut().text(res.data.response);
                        },4000);
                    }
                });
            }else {
                return false;
            }

        });

        setTimeout(function(){
            $('#flash-message').fadeOut().text(res.response);
        },4000);

    });

</script>