<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="DreamCloudTZ">

        <!---bootstrap4 ______start-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <!--FontAwesome Icons -->
        <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
        <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>

        <!-- JQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
        <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>

        <title>DreamCloudTZ</title>
    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="col-6 navbar-nav ml-auto mt-2 mt-lg-0 ">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <?php if(\Library\Session::get('role') == 'admin'):?>
                        <li class="nav-item">
                            <a class="nav-link" href="/users">All Users</a>
                        </li>
                    <?php endif;?>
                </ul>


                <?php if (\Library\Session::has('user')) : ?>
                        <form class="col-3 form-inline my-2 my-lg-0" method="post" action="/users">
                            <input name="tag" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                        <ul class="col-3 navbar-nav ml-auto mt-2 mt-lg-0 text-right justify-content-end">
                            <li class="nav-item right">
                                <a class="nav-link disabled" href="/logout">Logout (<?=\Library\Session::get('user')?>) role:<?=\Library\Session::get('role')?></a>
                            </li>
                        </ul>
                        <?php else: ?>
                        <ul class="col-3 navbar-nav ml-auto mt-2 mt-lg-0 text-right justify-content-end">
                            <li class="nav-item right">
                                <a class="nav-link disabled" href="/login">Login</a>
                            </li>
                        </ul>
                <?php endif ?>
            </div>
        </nav>

        <div class="container mt-2 text-center">
            <?php if($flash_message = \Library\Session::getFlash() ):?>
                <div id="flash_message" class="alert alert-info fixed-bottom text-center">
                    <?=$flash_message?>
                </div>
            <?php endif;?>
            <?=$content ?>
        </div>
    </body>
    <script>
        $(document).ready(function(){
            setTimeout(function(){
                $('#flash_message').fadeOut();
            },4000);
        });
    </script>
</html>


